#ifndef CONSTANTS_H
#define CONSTANTS_H

typedef enum
    {
    SOURCE_OTHER,

    SOURCE_1,
    SOURCE_2,
    SOURCE_3,
    SOURCE_4,

    SOURCE_NONE,

    NUMBER_OF_SOURCES
    }
SourcesEnum;

#define SOURCE_USAGE_MAXIMUM 10
#define SOURCE_USAGE_MINIMUM 3
#define OTHER_SOURCE_USAGE_MAXIMUM 10

#define MAIN_WINDOW_WIDTH 600 //300
#define MAIN_WINDOW_HEIGHT 1024 //610

#define DRAWING_AREA_Y_OFFSET 50
#define DRAWING_AREA_HEIGHT (MAIN_WINDOW_HEIGHT - DRAWING_AREA_Y_OFFSET)

#define SOURCE_1_R_COLOR 192
#define SOURCE_1_G_COLOR 131
#define SOURCE_1_B_COLOR 255

#define SOURCE_1_X_POSITION 305
#define SOURCE_1_Y_POSITION 214

#define SOURCE_2_R_COLOR 231
#define SOURCE_2_G_COLOR 220
#define SOURCE_2_B_COLOR 49

#define SOURCE_2_X_POSITION 305
#define SOURCE_2_Y_POSITION 344

#define SOURCE_3_R_COLOR 130
#define SOURCE_3_G_COLOR 170
#define SOURCE_3_B_COLOR 79

#define SOURCE_3_X_POSITION 305
#define SOURCE_3_Y_POSITION 484

#define SOURCE_4_R_COLOR 0
#define SOURCE_4_G_COLOR 204
#define SOURCE_4_B_COLOR 255

#define SOURCE_4_X_POSITION 305
#define SOURCE_4_Y_POSITION 619

#define CLOCK_HEARTBEAT_PERIOD_MILLISECONDS 60000

#define SEGMENTED_BAR_SLIDER_RANGE 437
#define SEGMENTED_BAR_OFFSET -18

#define VERTICAL_DATA_BAR_MAXIMUM_HEIGHT_PIXELS 276
#define VERTICAL_DATA_BAR_TIME_LABEL_HEIGHT_PIXELS 35
#define VERTICAL_DATA_BAR_TIME_FORMAT_STRING "%d:00%cm"

#define SLIDING_BAR_CHART_ANIMATION_DURATION_MILLISECONDS 1000
#define SLIDING_BAR_CHART_ANIMATION_FRAME_PERIOD_MILLISECONDS 25
#define SLIDING_BAR_CHART_ANIMATION_NUMBER_OF_FRAMES (SLIDING_BAR_CHART_ANIMATION_DURATION_MILLISECONDS / SLIDING_BAR_CHART_ANIMATION_FRAME_PERIOD_MILLISECONDS)

#define SLIDING_BAR_CHART_SOURCE_ANIMATION_DURATION_MILLISECONDS 700
#define SLIDING_BAR_CHART_SOURCE_ANIMATION_FRAME_PERIOD_MILLISECONDS 25
#define SLIDING_BAR_CHART_SOURCE_ANIMATION_NUMBER_OF_FRAMES (SLIDING_BAR_CHART_SOURCE_ANIMATION_DURATION_MILLISECONDS / SLIDING_BAR_CHART_SOURCE_ANIMATION_FRAME_PERIOD_MILLISECONDS)

#define SLIDING_BAR_CHART_FADEOUT_DURATION_MILLISECONDS 500
#define SLIDING_BAR_CHART_FADEOUT_FRAME_PERIOD_MILLISECONDS 25
#define SLIDING_BAR_CHART_FADEOUT_NUMBER_OF_FRAMES (SLIDING_BAR_CHART_FADEOUT_DURATION_MILLISECONDS / SLIDING_BAR_CHART_FADEOUT_FRAME_PERIOD_MILLISECONDS)
#define SLIDING_BAR_CHART_FADEOUT_STARTING_OPACITY 1.0
#define SLIDING_BAR_CHART_FADEOUT_DELTA_OPACITY (-(SLIDING_BAR_CHART_FADEOUT_STARTING_OPACITY))



// View 1

#define VIEW_1_CENTER_DISC_RADIUS 3
#define VIEW_1_CENTER_DISC_ALPHA_CHANNEL_FLOAT 0.15
#define VIEW_1_ANIMATION_DURATION_MILLISECONDS 900
#define VIEW_1_ANIMATION_FRAME_PERIOD_MILLISECONDS 30
#define VIEW_1_ANIMATION_NUMBER_OF_FRAMES (VIEW_1_ANIMATION_DURATION_MILLISECONDS / VIEW_1_ANIMATION_FRAME_PERIOD_MILLISECONDS)
#define VIEW_1_HEARTBEAT_PERIOD_MILLISECONDS 5000
#define VIEW_1_USAGE_MAXIMUM_DISC_SIZE 250
#define VIEW_1_SIMULATED_PER_MINUTE_DELTA_MAXIMA (int(SOURCE_USAGE_MAXIMUM * 1.0 / 1.2))
#define VIEW_1_MINIMUM_ACTUAL_VISIBLE_USAGE 0.2
#define VIEW_1_OUTER_EDGE_GRADIENT_ALPHA_CHANNEL_FLOAT 0.075
#define VIEW_1_SOURCE_NOT_SETUP_MESSAGE "Source not setup"

// SOURCE 1 COLORS

#define VIEW_1_STOP_1_SOURCE_1 0.0
#define VIEW_1_STOP_1_SOURCE_1_R_COLOR SOURCE_1_R_COLOR
#define VIEW_1_STOP_1_SOURCE_1_G_COLOR SOURCE_1_G_COLOR
#define VIEW_1_STOP_1_SOURCE_1_B_COLOR SOURCE_1_B_COLOR
#define VIEW_1_STOP_1_SOURCE_1_A_COLOR 255

#define VIEW_1_STOP_2_SOURCE_1 0.964626
#define VIEW_1_STOP_2_SOURCE_1_R_COLOR 206
#define VIEW_1_STOP_2_SOURCE_1_G_COLOR 158
#define VIEW_1_STOP_2_SOURCE_1_B_COLOR 255
#define VIEW_1_STOP_2_SOURCE_1_A_COLOR 150

#define VIEW_1_STOP_3_SOURCE_1 1.0
#define VIEW_1_STOP_3_SOURCE_1_R_COLOR 255
#define VIEW_1_STOP_3_SOURCE_1_G_COLOR 255
#define VIEW_1_STOP_3_SOURCE_1_B_COLOR 255
#define VIEW_1_STOP_3_SOURCE_1_A_COLOR 0

// SOURCE 2 COLORS

#define VIEW_1_STOP_1_SOURCE_2 0.0
#define VIEW_1_STOP_1_SOURCE_2_R_COLOR SOURCE_2_R_COLOR
#define VIEW_1_STOP_1_SOURCE_2_G_COLOR SOURCE_2_G_COLOR
#define VIEW_1_STOP_1_SOURCE_2_B_COLOR SOURCE_2_B_COLOR
#define VIEW_1_STOP_1_SOURCE_2_A_COLOR 255

#define VIEW_1_STOP_2_SOURCE_2 0.964626
#define VIEW_1_STOP_2_SOURCE_2_R_COLOR 231
#define VIEW_1_STOP_2_SOURCE_2_G_COLOR 220
#define VIEW_1_STOP_2_SOURCE_2_B_COLOR 49
#define VIEW_1_STOP_2_SOURCE_2_A_COLOR 150

#define VIEW_1_STOP_3_SOURCE_2 1.0
#define VIEW_1_STOP_3_SOURCE_2_R_COLOR 255
#define VIEW_1_STOP_3_SOURCE_2_G_COLOR 255
#define VIEW_1_STOP_3_SOURCE_2_B_COLOR 255
#define VIEW_1_STOP_3_SOURCE_2_A_COLOR 0

// SOURCE 3 COLORS

#define VIEW_1_STOP_1_SOURCE_3 0.0
#define VIEW_1_STOP_1_SOURCE_3_R_COLOR SOURCE_3_R_COLOR
#define VIEW_1_STOP_1_SOURCE_3_G_COLOR SOURCE_3_G_COLOR
#define VIEW_1_STOP_1_SOURCE_3_B_COLOR SOURCE_3_B_COLOR
#define VIEW_1_STOP_1_SOURCE_3_A_COLOR 255

#define VIEW_1_STOP_2_SOURCE_3 0.964626
#define VIEW_1_STOP_2_SOURCE_3_R_COLOR 130
#define VIEW_1_STOP_2_SOURCE_3_G_COLOR 170
#define VIEW_1_STOP_2_SOURCE_3_B_COLOR 79
#define VIEW_1_STOP_2_SOURCE_3_A_COLOR 150

#define VIEW_1_STOP_3_SOURCE_3 1.0
#define VIEW_1_STOP_3_SOURCE_3_R_COLOR 255
#define VIEW_1_STOP_3_SOURCE_3_G_COLOR 255
#define VIEW_1_STOP_3_SOURCE_3_B_COLOR 255
#define VIEW_1_STOP_3_SOURCE_3_A_COLOR 0

// SOURCE 4 COLORS

#define VIEW_1_STOP_1_SOURCE_4 0.0
#define VIEW_1_STOP_1_SOURCE_4_R_COLOR SOURCE_4_R_COLOR
#define VIEW_1_STOP_1_SOURCE_4_G_COLOR SOURCE_4_G_COLOR
#define VIEW_1_STOP_1_SOURCE_4_B_COLOR SOURCE_4_B_COLOR
#define VIEW_1_STOP_1_SOURCE_4_A_COLOR 255

#define VIEW_1_STOP_2_SOURCE_4 0.964626
#define VIEW_1_STOP_2_SOURCE_4_R_COLOR 0
#define VIEW_1_STOP_2_SOURCE_4_G_COLOR 204
#define VIEW_1_STOP_2_SOURCE_4_B_COLOR 255
#define VIEW_1_STOP_2_SOURCE_4_A_COLOR 150

#define VIEW_1_STOP_3_SOURCE_4 1.0
#define VIEW_1_STOP_3_SOURCE_4_R_COLOR 255
#define VIEW_1_STOP_3_SOURCE_4_G_COLOR 255
#define VIEW_1_STOP_3_SOURCE_4_B_COLOR 255
#define VIEW_1_STOP_3_SOURCE_4_A_COLOR 0



// View 2

//#define VIEW_2_WEATHER_CHANGE_PERIOD_MINUTES 0.1
//#define VIEW_2_WEATHER_CHANGE_PERIOD_MILLISECONDS (VIEW_2_WEATHER_CHANGE_PERIOD_MINUTES * 60000)
#define VIEW_2_MAX_TEMPERATURE 120
#define VIEW_2_MIN_TEMPERATURE -60
#define VIEW_2_HIGH_TEMPERATURE_FORMAT_STRING "H: %d\302\260" //"H: %d°"
#define VIEW_2_LOW_TEMPERATURE_FORMAT_STRING "L: %d\302\260" //"L: %d°"
#define VIEW_2_NOTES_FOLDER "notes/"
#define VIEW_2_NOTE_FILENAME_TEMPLATE "%d.txt"
#define VIEW_2_VIEW_NOTE_TITLE_TEMPLATE "Notes on %s"
#define VIEW_2_EDIT_NOTE_TITLE_TEMPLATE "Edit on %s"
#define VIEW_2_TITLE_TEXT "Daily Data by Individual Source"

#define VIEW_2_SEGMENTED_BAR_X_POSITION 0
#define VIEW_2_SEGMENTED_BAR_Y_POSITION 100

#define VIEW_2_OTHER_SOURCES_LABEL "Other Sources"

#define VIEW_2_SLIDING_BAR_CHAR_X_POSITION 0
#define VIEW_2_SLIDING_BAR_CHAR_Y_POSITION 350


// View 3

#define VIEW_3_SEGMENTED_BAR_X_POSITION 0
#define VIEW_3_SEGMENTED_BAR_Y_POSITION 100
#define VIEW_3_PREV_MONTH_X 900
#define VIEW_3_NEXT_MONTH_X 900
#define VIEW_3_MONTH_X 25
#define VIEW_3_MONTH_ANIMATION_INTERVAL 25
#define VIEW_3_MONTH_SCROLLINGANIMATION_INTERVAL 500

// View 4

#define VIEW_4_YEAR_DISPLAY_TEMPLATE "%s - %s"
#define VIEW_4_SEGMENTED_BAR_X_POSITION 0
#define VIEW_4_SEGMENTED_BAR_Y_POSITION 100

#define VIEW_4_SLIDING_BAR_CHAR_X_POSITION 0
#define VIEW_4_SLIDING_BAR_CHAR_Y_POSITION 350

#endif // CONSTANTS_H
